namespace WpfFungusApp.DBStore
{
    class PostgreSQLImagePathsStore : ImagePathsStore, IImagePathsStore
    {
        public PostgreSQLImagePathsStore(PetaPoco.Database database) : base(database)
        {
            UseTableNameFix = true;
        }

        public override void CreateTable()
        {
            _database.Execute("CREATE TABLE \"tblImagesDatabase\" (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, path VARCHAR(255) UNIQUE);");
        }
    }
}
